# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Maven build
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Debug: List files in working directory
- script: |
    echo "Listing files in the working directory after Maven build:"
    ls -R $(System.DefaultWorkingDirectory)
  displayName: 'Debug: List working directory'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/target'
    artifactName: 'warfile'
    publishLocation: 'Container'

# Docker login
- task: Docker@2
  inputs:
    containerRegistry: 'rafdocker1'
    command: 'login'

# Docker build and push
- task: Docker@2
  inputs:
    containerRegistry: 'rafdocker1'
    repository: 'sonako2000/azuredevops-1'
    command: 'buildAndPush'
    dockerfile: 'AzureDockerfile'



